name = "caveful_games/rbxclothing"
version = "0.1.0"
authors = ["kimpure"]
license = "MIT"
includes = [ "pesde.toml", "readme.md", "licence.md", "src/**" ]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.1", target = "lune" }
luau_futures = { name = "yetanotherclown/luau_futures", version = "^2.0.0-beta.3", target = "luau" }
