name = "caveful_games/rbxclothing"
version = "0.1.0"
authors = ["kimpure"]
license = "MIT"
includes = [ "pesde.toml", "README.md", "LICENSE", "src/**" ]
description = "rbxclothing is a library that allows you to put on pants and shirts using EditableImage without using Humanoid"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

build = "scripts/build.luau"

[engines]
lune = "^0.9.4"
pesde = "^0.7.0-rc.1"

[dev_dependencies]
scripts = { name = "jiwonz/pesde_scripts_rojo", version = "^0.1.0-rc.1", target = "lune" }

[dependencies]
greentea = { name = "corecii/greentea", version = "^0.4.11" }
